api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "custom-rug-product"
type = "function"
uid = "144abee4-97f3-26f1-59cd-ef4489066e26200889b9"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
